services:
  - type: web
    name: mailcannon
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
